"""Add order_index to formulas

Revision ID: 823b30b2a10e
Revises: 4decd4dac74b
Create Date: 2026-05-03 20:46:08.209623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '823b30b2a10e'
down_revision: Union[str, None] = '4decd4dac74b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula_entries', sa.Column('order_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula_entries', 'order_index')
    # ### end Alembic commands ###
